### ISSUE TITLE
Doesnt record my actual phone number

### ISSUE THREAD

**Issue by zmitton** [blocknotary/proofofphone#3]
I just tried it out and my data looks as so:

phone:0
payment: 1
data:  e74c906589b9a59682ebe40731f8ef794078be5b

Looking at the code seems like I should have called the function newPhoneToAddress? I was never told that however.

Seems like a good idea though.

**Comment by igorbarinov** [comment]
Hi, thanks for reporting. Sorry about that. We will figure out this bug and refund your payment.

**Comment by zmitton** [comment]
No problem. Happy to help.

**Comment by vbaranov** [comment]
Hi, we refunded your payment and made changes to smart contract definition.
You can try to join your phone to wallet: 
get code by sms -> enter this code into web form -> send ether to contract with a hash message -> enter your address to web form and submit.
If any problem still exists, please, let us know.

**Comment by igorbarinov** [comment]
@zmitton Zac, can you please test one more time? We appreciate it

**Comment by zmitton** [comment]
Sure. Give me an hour or so and I'll let you know

On Wednesday, May 25, 2016, Igor Barinov notifications@github.com wrote:

> @zmitton https://github.com/zmitton Zac, can you please test one more
> time? We appreciate it
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/blocknotary/proofofphone/issues/3#issuecomment-221777671

## 

Thanks,
Zac

**Comment by igorbarinov** [comment]
@zmitton Hi Zac, any luck to test the proof of phone? Thanks in advance!
